Courts organization
matcom/dashboard pull request #24
Opened 2022-11-20 00:20 UTC by cmglezpdev

## Funcionalidades nuevas

- Se añadió una sección para poder crear tribunales y editar los ya creados. Estos requieren privilegios de administrador.
- Por cada tribunal se deben añadir:
    -  _tesis, miembros del tribunal, fecha, hora, tiempo de duración, local para la discución de la tesis_
- Al crear un tribunal este verifica que:
    - No cree dos tribunales para una misma tesis.
    - Dos personas no esten en dos tesis al mismo tiempo
    - No existan dos tesis en el mismo local al mismo tiempo
- Se añadió una vista para ver  todos los tribunales, estos se pueden organizar por cualquiera de sus propiedades y también ser filtrados por _Miembros del tribunal_ y _fecha_

<hr />

Con respecto al código se añadieron dos modelos nuevos:
     - __Court__: representa un tribunal
     - __Place__: representa los sitios donde se discutirán las tesis

2022-11-21 20:53 UTC, apiad requested changes
Está espectacular! Lo único que quisiera cambiar es que en vez de impedir guardar un tribunal si hay conflictos, simplemente de un warning en el momento en que se seleccionan fecha / lugar / personas que crearían conflictos pero aún así dejar guardarlo.

Luego en la vista donde están todos los tribunales, poner un ícono al lado de los tribunales que tengan algún conflicto.

2022-11-21 20:53 UTC, apiad commented
Closes #22

2022-11-22 02:30 UTC, cmglezpdev commented
## Cambios agregados

- Se añadió el mensaje de warning al crear la tesis pero aun asi se puede crear(en los caso que se especificaron)
- Se añadió el ícono de __warning__ al principio del nombre de la tesis en la vista general de todos tribunales

2022-11-22 02:38 UTC, cmglezpdev commented
## Cambios agregados

- Se añadió el mensaje de warning al crear la tesis pero aun asi se puede crear(en los caso que se especificaron)
- Se añadió el ícono de __warning__ al principio del nombre de la tesis en la vista general de todos tribunales
- También cambié la comparación que hacía entre las fechas para que se pudiera añadir un tribunal justo en el último minuto que termina la anterior o añadir una antes y que termine en el minuto que empiece la siguiente(antes esto decía que estaba ocupada)

2023-01-20 06:14 UTC, closed without merging