Se implemento el routing de las paginas de acuerdo con #39
matcom/dashboard pull request #40
Opened 2023-04-21 01:08 UTC by vekt0R-HUB

Se implemento el routing de las paginas que faltaban. Se hizo de acuerdo en el issue #39 . Se hizo subcarpeta para todos las paginas y se dejo en el .py solo el routing

2023-04-21 03:22 UTC, jmorgadov requested changes
@vekt0R-HUB en los builder de cada páginas luego de cada `set_page_config` cambia (o pon donde falte) los que tengan un `st.title` y usa el método `page_header` del `router`. Ese método pone el title de la página y muestra además un back button y un botón para cambiar permisos en caso de que el usuario pueda hacerlo.

2023-04-21 14:49 UTC, jmorgadov approved these changes

2023-04-21 15:47 UTC, jmorgadov approved these changes

2023-04-26 13:47 UTC, apiad approved these changes

2023-04-26 13:47 UTC, merged